update gstreamer to 1.16.0
The build failed with
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread -DGST_USE_UNSTABLE_API -fno-strict-aliasing -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -Wall -Wdeclaration-after-statement -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wwrite-strings -Wformat-security -Wold-style-definition -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wnested-externs -g -fvisibility=hidden -march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -MT libgstdtls_la-gstdtlsdec.lo -MD -MP -MF .deps/libgstdtls_la-gstdtlsdec.Tpo -c gstdtlsdec.c  -fPIC -DPIC -o .libs/libgstdtls_la-gstdtlsdec.o
gstfdkaacenc.c:74:8: error: ‘MODE_2_1’ undeclared here (not in a function); did you mean ‘MODE_6_1’?
     3, MODE_2_1, {
        ^~~~~~~~
        MODE_6_1
make[3]: *** [Makefile:875: libgstfdkaac_la-gstfdkaacenc.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -I../../gst-libs -I../../gst-libs -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread  -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread  -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread   -DGST_USE_UNSTABLE_API -fno-strict-aliasing  -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -Wall -Wdeclaration-after-statement -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wwrite-strings -Wformat-security -Wold-style-definition -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wnested-externs   -g    -fvisibility=hidden    -march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -MT libgsthls_la-gsthlsdemux.lo -MD -MP -MF .deps/libgsthls_la-gsthlsdemux.Tpo -c -o libgsthls_la-gsthlsdemux.lo `test -f 'gsthlsdemux.c' || echo './'`gsthlsdemux.c
gstfdkaacdec.c: In function ‘gst_fdkaacdec_set_format’:
gstfdkaacdec.c:162:43: error: ‘AAC_PCM_OUTPUT_INTERLEAVED’ undeclared (first use in this function); did you mean ‘AAC_PCM_OUTPUT_CHANNEL_MAPPING’?
           aacDecoder_SetParam (self->dec, AAC_PCM_OUTPUT_INTERLEAVED,
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                           AAC_PCM_OUTPUT_CHANNEL_MAPPING
gstfdkaacdec.c:162:43: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [Makefile:882: libgstfdkaac_la-gstfdkaacdec.lo] Error 1
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread  -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread  -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread   -DGST_USE_UNSTABLE_API -fno-strict-aliasing  -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -Wall -Wdeclaration-after-statement -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wwrite-strings -Wformat-security -Wold-style-definition -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wnested-externs   -g    -fvisibility=hidden  -march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -MT libgstdtls_la-gstdtlsenc.lo -MD -MP -MF .deps/libgstdtls_la-gstdtlsenc.Tpo -c -o libgstdtls_la-gstdtlsenc.lo `test -f 'gstdtlsenc.c' || echo './'`gstdtlsenc.c
mv -f .deps/libgstdtls_la-plugin.Tpo .deps/libgstdtls_la-plugin.Plo
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread  -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread  -I/app/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -pthread   -DGST_USE_UNSTABLE_API -fno-strict-aliasing  -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -Wall -Wdeclaration-after-statement -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wwrite-strings -Wformat-security -Wold-style-definition -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wnested-externs   -g    -fvisibility=hidden -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid  -march=x86-64 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -MT libgstttmlsubs_la-gstttmlparse.lo -MD -MP -MF .deps/libgstttmlsubs_la-gstttmlparse.Tpo -c -o libgstttmlsubs_la-gstttmlparse.lo `test -f 'gstttmlparse.c' || echo './'`gstttmlparse.c
mv -f .deps/libgstfdkaac_la-plugin.Tpo .deps/libgstfdkaac_la-plugin.Plo
make[3]: Leaving directory '/run/build/gst-plugins-bad/ext/fdkaac'
make[2]: *** [Makefile:1316: fdkaac] Error 2

Let's hope an update fixes that problem.