update zxing to build
It failed:

/run/build/zxing/core/src/textcodec/JPTextEncoder.cpp:2207:54: error:
‘uint8_t’ does not name a type
2207 |                         bytes[index++] = static_cast<uint8_t>((j
& 0xff) | 0x80);
      |                                                      ^~~~~~~
/run/build/zxing/core/src/textcodec/JPTextEncoder.cpp:2207:54: note:
‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by
adding ‘#include <cstdint>’