update libical to overcome build error
[ 98%] Linking C executable testvcal
Scanning dependencies of target process
[ 98%] Building C object src/test/CMakeFiles/process.dir/process.c.o
[ 98%] Linking C executable icaltm_test
[ 98%] Built target testvcal
[ 99%] Linking C executable process
/run/build/libical/src/libical-glib/i-cal-object.c: In function
‘i_cal_object_class_init’:
/run/build/libical/src/libical-glib/i-cal-object.c:136:5: warning:
‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
  136 |     g_type_class_add_private(class, sizeof(ICalObjectPrivate));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from
/run/build/libical/src/libical-glib/i-cal-object.h:26,
                 from
/run/build/libical/src/libical-glib/i-cal-object.c:21:
/usr/include/glib-2.0/gobject/gtype.h:1308:10: note: declared here
1308 | void     g_type_class_add_private       (gpointer
                    g_class,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
/run/build/libical/src/libical-glib/i-cal-object.c: In function
‘i_cal_object_init’:
/run/build/libical/src/libical-glib/i-cal-object.c:212:13: warning:
G_ADD_PRIVATE
  212 |     iobject->priv = G_TYPE_INSTANCE_GET_PRIVATE(iobject,
I_CAL_TYPE_OBJECT, ICalObjectPrivate);
      |             ^~~~~~~~~~~~~~~
[ 99%] Linking C shared library ../../lib/libical-glib.so
[ 99%] Built target icaltm_test
[ 99%] Built target process
[ 99%] Built target ical-glib
Scanning dependencies of target documentation
[ 99%] Generating xml/libical-glib-doc.bottom
/run/build/libical/src/libical-glib/i-cal-geo-type.h:0: warning: partial
declaration (struct) : struct icalgeotype
		i_cal_geo_type_new_default	(void);

LIBICAL_ICAL_EXPORT
gdouble 		i_cal_geo_type_get_lat
(ICalGeoType *geo_type);

LIBICAL_ICAL_EXPORT
void		i_cal_geo_type_set_lat		(ICalGeoType
*geo_type,
						 gdouble lat);

LIBICAL_ICAL_EXPORT
gdouble 		i_cal_geo_type_get_lon
(ICalGeoType *geo_type);

LIBICAL_ICAL_EXPORT
void		i_cal_geo_type_set_lon		(ICalGeoType
*geo_type,
						 gdouble lon);

G_END_DECLS

/run/build/libical/src/libical-glib/tools/generator.c:703: warning:
Symbol name not found at the start of the comment block.
unknown:0: warning: Value descriptions for ICalParameterKind are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterAction are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterCutype are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterEnable are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterEncoding are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterFbtype are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterLocal are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterPartstat are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterRange are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterRelated are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterReltype are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterRequired are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterRole are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterRsvp are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterScheduleagent
are missing in source code comment block.
unknown:0: warning: Value descriptions for
ICalParameterScheduleforcesend are missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterStayinformed are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterSubstate are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterValue are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterXliccomparetype
are missing in source code comment block.
unknown:0: warning: Value descriptions for ICalParameterXlicerrortype
are missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyKind are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalValueKind are missing in
source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyAction are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyBusytype are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyCarlevel are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalProperty_Class are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyCmd are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyMethod are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyPollcompletion
are missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyPollmode are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyQuerylevel are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyStatus are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyTaskmode are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyTransp are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalPropertyXlicclass are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalComponentKind are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalRequestStatus are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalErrorEnum are missing in
source code comment block.
unknown:0: warning: Value descriptions for ICalErrorState are missing in
source code comment block.
unknown:0: warning: Value descriptions for ICalParserState are missing
in source code comment block.
unknown:0: warning: Value descriptions for ICalRecurrenceTypeFrequency
are missing in source code comment block.
unknown:0: warning: Value descriptions for ICalRecurrenceTypeWeekday are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalRecurrenceTypeSkip are
missing in source code comment block.
unknown:0: warning: Value descriptions for
ICalRecurrenceTypeArrayMaxValues are missing in source code comment
block.
unknown:0: warning: Value descriptions for ICalRestrictionKind are
missing in source code comment block.
unknown:0: warning: Value descriptions for ICalUnknowntokenhandling are
missing in source code comment block.
unknown:0: warning: Field descriptions for struct Parameter are missing
in source code comment block.
unknown:0: warning: Field descriptions for struct Ret are missing in
source code comment block.
unknown:0: warning: Field descriptions for struct Method are missing in
source code comment block.
unknown:0: warning: Field descriptions for struct Structure are missing
in source code comment block.
unknown:0: warning: Field descriptions for struct Declaration are
missing in source code comment block.
unknown:0: warning: Field descriptions for struct Enumeration are
missing in source code comment block.
./libical-glib-unused.txt:1: warning: 7 unused declarations. They should
be added to libical-glib-sections.txt in the appropriate place.
[ 99%] Generating libical-glib documentation
warning: failed to load external entity "../xml/i-cal-geo-type.xml"
../libical-glib-docs.xml:28: element include: XInclude error : could not
load ../xml/i-cal-geo-type.xml, and no fallback was found
make[2]: ***
[doc/reference/libical-glib/CMakeFiles/documentation.dir/build.make:63:
doc/reference/libical-glib/html/index.html] Error 6
make[1]: *** [CMakeFiles/Makefile2:1319:
doc/reference/libical-glib/CMakeFiles/documentation.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Error: module libical: Child process exited with code 2
FB: unmounting rofiles-fuse
/home/muelli/vcs/org.gnome.Keysign/.flatpak-builder/rofiles/rofiles-l06Bn7